import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { mindmapSourceFingerprint } from "./mindmap-source";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const require = createRequire(import.meta.url);
const esbuild = require("esbuild") as {
  build: (options: Record<string, unknown>) => Promise<{
    outputFiles: Array<{ contents: Uint8Array }>;
  }>;
};

const result = await esbuild.build({
  entryPoints: [join(root, "web/mindmap/client.ts")],
  bundle: true,
  minify: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  write: false,
});
const bytes = result.outputFiles[0]?.contents ?? new Uint8Array();
const bundle = new TextDecoder().decode(bytes);
for (const marker of ["#memory-map", "mindmap/data"]) {
  if (!bundle.includes(marker)) throw new Error(`mindmap bundle missing marker: ${marker}`);
}

const output = `import type { MindmapClientCopy } from "./mindmap-copy";

/** Generated by \`yarn build:mindmap\`. Do not edit; change web/mindmap/*.ts instead. */
const SOURCE_FINGERPRINT = "${mindmapSourceFingerprint()}";

const BUNDLE_JS = ${JSON.stringify(bundle)};

/** Source fingerprint so \`yarn check:mindmap\` and tests fail when the bundle is stale. */
export function mindmapBundleFingerprint(): string {
  return SOURCE_FINGERPRINT;
}

export function buildMindmapClientScript(copy: MindmapClientCopy): string {
  return \`window.__mempersistMindmap=\${JSON.stringify(copy)};\${BUNDLE_JS}\`;
}
`;
writeFileSync(join(root, "src/mindmap-bundle.ts"), output);
console.log(`mindmap bundle bytes=${String(bundle.length)}`);
